// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDQtvFXEeNu4zvFeYUD1rvp0LHkKZg3_k',
    appId: '1:53728937912:android:33f0e8d344ee98e8a4b14d',
    messagingSenderId: '53728937912',
    projectId: 'upload-image-firebase-62f4f',
    storageBucket: 'upload-image-firebase-62f4f.appspot.com',
    databaseURL: 'https://console.firebase.google.com/project/upload-image-firebase-62f4f/database/upload-image-firebase-62f4f-default-rtdb/data/~2F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuj1mZsnyTumc3qvW1lSrSSCZSFoAYy7A',
    appId: '1:53728937912:ios:0700752c8f846564a4b14d',
    messagingSenderId: '53728937912',
    projectId: 'upload-image-firebase-62f4f',
    storageBucket: 'upload-image-firebase-62f4f.appspot.com',
    iosBundleId: 'com.uploadimagefirebase.uploadImageFirebase',
    databaseURL: 'https://console.firebase.google.com/project/upload-image-firebase-62f4f/database/upload-image-firebase-62f4f-default-rtdb/data/~2F',
  );
}
